### ISSUE TITLE
Fonts don't work when converting to HTML

### ISSUE THREAD

**Issue by alvii147** [Y1chenYao/typora-mint-theme#10]
The fonts don't work when converted to HTML and just defaults to Times New Roman:

![image](https://user-images.githubusercontent.com/35665983/144008887-abe4e0c9-7737-47f7-9103-45697a056ec3.png)

The solution to this is probably including a CSS `@font-face` definition in the HTML.

```css
@font-face {
	font-family: 'Lexend';
	src: url('Lexend-Regular.ttf') format('truetype');
}
```

Note that this means users will have to put `Lexend-Regular.ttf` in the same directory as the HTML.
